### ISSUE TITLE
Bug: ESLint no-undef error for 'isOpen' in ModernAbout.js (Regression from #1229)

### ISSUE THREAD

**Issue by nisha-bugalia** [SandeepVashishtha/Eventra#1259]
### Describe the bug

Describe the bug A recent chore PR (#1229) aimed at resolving ESLint warnings inadvertently removed a required variable in src/Pages/About/ModernAbout.js, causing a no-undef ESLint error that breaks the compilation/UI for the About page.

### To Reproduce

To Reproduce Steps to reproduce the behavior:

Pull the latest master branch.
Run npm start.
Navigate to the About page (/about).
See the compilation error:

src\Pages\About\ModernAbout.js
  Line 245:16:  'isOpen' is not defined  no-undef

### Expected behavior

Expected behavior The page should compile successfully and the CountUp animation for active users should trigger when scrolled into view.

### Additional context

**Root Cause**
In PR #1229, under the assumption that `isOpen` was an unused state value, the array destructuring on line 184 was changed from:
```javascript
const [isOpen, setIsOpen] = useState(false);
```
to:
```javascript
const [, setIsOpen] = useState(false);
```

However, `isOpen` is actively used on line 245 to conditionally render the `CountUp` animation:
```javascript
{isOpen ? <CountUp start={0} end={500} duration={3} suffix="+" /> : "0+"}
```

**Proposed Solution**
Restore the `isOpen` variable to the `useState` hook destructuring array:
```javascript
const [isOpen, setIsOpen] = useState(false);
```

I have this fix tested locally and can submit a Pull Request to resolve this if approved!

Please assign this issue to me!!

**Comment by dhruvnayak001** [comment]
Hi @SandeepVashishtha 

I’d like to take this up under GSSoC 2026. I’ve analyzed the regression introduced in PR #1229 and the issue appears to be caused by removal of isOpen from the useState destructuring in ModernAbout.js.

Since isOpen is still being referenced in the JSX conditional rendering for the CountUp component (line ~245), ESLint correctly throws a no-undef error, which also breaks the build for the About page.

Root cause: state variable incorrectly removed during cleanup of unused variables

Fix: restore the state declaration:

const [isOpen, setIsOpen] = useState(false);

I’ve verified this locally and confirmed the About page compiles and the CountUp animation triggers correctly on scroll after the fix.

If this looks good, please assign this issue to me and I’ll raise a PR with the fix.
